In [189]:
import pandas as pd

In [190]:
import numpy as np

In [191]:
import matplotlib.pyplot as plt

In [192]:
import seaborn as sns

# import data

In [193]:
df = pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Teaching-Data/main/Women%20Clothing%20E-Commerce%20Review.csv')

In [194]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [196]:
df.shape

(23486, 10)

In [197]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [198]:
df[df['Review']==""]=np.NaN

In [199]:
df['Review'].fillna("No Review",inplace=True)

In [200]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [201]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# Define Target(y) and feature (X)

In [202]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [203]:
x = df["Review"]

In [204]:
y = df["Rating"]

In [205]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [206]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [207]:
df.info

<bound method DataFrame.info of        Clothing ID  Age                                              Title  \
0              767   33                                                NaN   
1             1080   34                                                NaN   
2             1077   60                            Some major design flaws   
3             1049   50                                   My favorite buy!   
4              847   47                                   Flattering shirt   
...            ...  ...                                                ...   
23481         1104   34                     Great dress for many occasions   
23482          862   48                         Wish it was made of cotton   
23483         1104   31                              Cute, but see through   
23484         1084   28  Very cute dress, perfect for summer parties an...   
23485         1104   52                    Please make more like this one!   

                                                  Review  Rating  Recommended  \
0      Absolutely wonderful - silky and sexy and comf...       4            1   
1      Love this dress!  it's sooo pretty.  i happene...       5            1   
2      I had such high hopes for this dress and reall...       3            0   
3      I love, love, love this jumpsuit. it's fun, fl...       5            1   
4      This shirt is very flattering to all due to th...       5            1   
...                                                  ...     ...          ...   
23481  I was very happy to snag this dress at such a ...       5            1   
23482  It reminds me of maternity clothes. soft, stre...       3            1   
23483  This fit well, but the top was very see throug...       3            0   
23484  I bought this dress for a wedding i have this ...       3            1   
23485  This dress in a lovely platinum is feminine an...       5            1   

       Positive Feedback        Division Department   Category  
0                      0       Initmates   Intimate  Intimates  
1                      4         General    Dresses    Dresses  
2                      0         General    Dresses    Dresses  
3                      0  General Petite    Bottoms      Pants  
4                      6         General       Tops    Blouses  
...                  ...             ...        ...        ...  
23481                  0  General Petite    Dresses    Dresses  
23482                  0  General Petite       Tops      Knits  
23483                  1  General Petite    Dresses    Dresses  
23484                  2         General    Dresses    Dresses  
23485                 22  General Petite    Dresses    Dresses  

[23486 rows x 10 columns]>

In [208]:
df.shape

(23486, 10)

In [209]:
df.isna().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of        Clothing ID    Age  Title  Review  Rating  Recommended  \
0            False  False   True   False   False        False   
1            False  False   True   False   False        False   
2            False  False  False   False   False        False   
3            False  False  False   False   False        False   
4            False  False  False   False   False        False   
...            ...    ...    ...     ...     ...          ...   
23481        False  False  False   False   False        False   
23482        False  False  False   False   False        False   
23483        False  False  False   False   False        False   
23484        False  False  False   False   False        False   
23485        False  False  False   False   False        False   

       Positive Feedback  Division  Department  Category  
0                  False     False       False     False  
1                  False     False       False     False  
2                  False     False       False     False  
3                  False     False       False     False  
4                  False     False       False     False  
...                  ...       ...         ...       ...  
23481              False     False       False     False  
23482              False     False       False     False  
23483              False     False       False     False  
23484              False     False       False     False  
23485              False     False       False     False  

[23486 rows x 10 columns]>

In [210]:
df[df['Review']==""]=np.NaN

In [211]:
df['Review'].fillna("No Review",inplace=True)

In [212]:
df.isna().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of        Clothing ID    Age  Title  Review  Rating  Recommended  \
0            False  False   True   False   False        False   
1            False  False   True   False   False        False   
2            False  False  False   False   False        False   
3            False  False  False   False   False        False   
4            False  False  False   False   False        False   
...            ...    ...    ...     ...     ...          ...   
23481        False  False  False   False   False        False   
23482        False  False  False   False   False        False   
23483        False  False  False   False   False        False   
23484        False  False  False   False   False        False   
23485        False  False  False   False   False        False   

       Positive Feedback  Division  Department  Category  
0                  False     False       False     False  
1                  False     False       False     False  
2                  False     False       False     False  
3                  False     False       False     False  
4                  False     False       False     False  
...                  ...       ...         ...       ...  
23481              False     False       False     False  
23482              False     False       False     False  
23483              False     False       False     False  
23484              False     False       False     False  
23485              False     False       False     False  

[23486 rows x 10 columns]>

In [213]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# define target(y) and feature(x)

In [214]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [215]:
X = df["Review"]

In [216]:
y = df['Rating']

In [217]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

# Train test split

In [218]:
from sklearn.model_selection import train_test_split

In [219]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, stratify = y, random_state = 2529)

In [220]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get feature text conversion to tokens

In [221]:
from sklearn.feature_extraction.text import CountVectorizer

In [222]:
cv= CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2, 3), stop_words = 'english', max_features=5000)

In [223]:
X_train = cv.fit_transform(X_train)

In [224]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [225]:
X_train.toarray

<bound method _cs_matrix.toarray of <16440x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 124363 stored elements in Compressed Sparse Row format>>

In [226]:
X_test = cv.fit_transform(X_test)

In [227]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [228]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Get Model Train

In [229]:
from sklearn.naive_bayes import MultinomialNB

In [230]:
model = MultinomialNB()

In [231]:
model.fit(X_train, y_train)
MultinomialNB()

MultinomialNB()

# Get model prediction

In [232]:
y_pred = model.predict(X_test)

In [233]:
y_pred.shape

(7046,)

In [234]:
y_pred

array([1, 5, 5, ..., 5, 5, 5])

# get probability of each predicted class

In [235]:
model.predict_proba(X_test)

array([[0.71118473, 0.02625165, 0.15465118, 0.01496876, 0.09294369],
       [0.02416867, 0.04769471, 0.35268622, 0.16185007, 0.41360034],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.02320281, 0.08950939, 0.08962183, 0.16719203, 0.63047394],
       [0.01167675, 0.00202714, 0.08539004, 0.34347398, 0.55743209],
       [0.03959824, 0.05612822, 0.00688869, 0.1560574 , 0.74132745]])

# get model evaluation

In [236]:
from sklearn.metrics import confusion_matrix, classification_report

In [237]:
print(confusion_matrix(y_test, y_pred))

[[  15   13   45   36  144]
 [  43   43   86   85  213]
 [ 116   78  113  166  388]
 [ 166  108  194  336  719]
 [ 371  272  349  722 2225]]


# recategories ratings as poor(0) and good (1)

In [238]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [239]:
df.replace({'Rating' : { 1 : 0, 2 : 0, 3 : 0, 4 : 1, 5 : 1 }},inplace = True)

In [240]:
y = df['Rating']

In [241]:
X = df['Review']

# train test split

In [242]:
from sklearn.model_selection import train_test_split

In [243]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, stratify = y, random_state = 2529)

In [244]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# get feature text conversion to tokens

In [245]:
from sklearn.feature_extraction.text import CountVectorizer

In [246]:
cv= CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2, 3), stop_words =  'english', max_features=5000)

In [247]:
X_train = cv.fit_transform(X_train)

In [248]:
X_test  = cv.fit_transform(X_test)

# get model re-train

In [249]:
from sklearn.naive_bayes import MultinomialNB

In [250]:
model = MultinomialNB()

In [251]:
model.fit(X_train, y_train)

MultinomialNB()

# get model prediction

In [252]:
y_pred = model.predict(X_test)

In [253]:
y_pred.shape

(7046,)

In [254]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

# get model evaluation

In [255]:
from sklearn.metrics import confusion_matrix, classification_report

In [256]:
print(confusion_matrix(y_test, y_pred))

[[ 449 1134]
 [ 989 4474]]


In [257]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.31      0.28      0.30      1583
           1       0.80      0.82      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.69      7046

